### ISSUE TITLE
Error when starting pihole_exporter.py

### ISSUE THREAD

**Issue by wjanes** [dr1s/pihole_exporter.py#1]
Hi Dr1s

I just tried your pihole_exporter without arguments and get the following error:
I am hosting pihole and prometheus on the same machine ( localhost )

```
[2018-01-11 18:09:37,138] ERROR in app: Exception on /metrics [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./pihole_exporter.py", line 57, in metrics
    top_queries = top_items['top_queries']
TypeError: list indices must be integers or slices, not str
```
BR Wolfgang

**Comment by dr1s** [comment]
Hi Wolfgang,

Do you have password authentication enabled on pihole?

**Comment by wjanes** [comment]
Hi. Yes. I just sämtliche that IT worked when i Used the api token.

Thank you

BR Wolfgang

**Comment by dr1s** [comment]
Glad to know it works for you.

Viel Spaß ;)
