### ISSUE TITLE
IPv6 not possible anymore

### ISSUE THREAD

**Issue by Madic-** [dr1s/pihole_exporter.py#4]
Hey,

with version 0.1 your exporter could listen on IPv6 Addresses (--interface ::).
With version 0.3 it's not possible anymore. I suppose because you've removed flask.

Error I get when I try to start with --interface ::

> * Listening on :::9311
Traceback (most recent call last):
  File "./pihole_exporter", line 11, in <module>
    load_entry_point('pihole-exporter==0.3.dev0', 'console_scripts', 'pihole_exporter')()
  File "/opt/pihole-exporter/lib/python3.5/site-packages/pihole_exporter/pihole_exporter.py", line 154, in main
    exporter.make_server(args.interface, args.port)
  File "/opt/pihole-exporter/lib/python3.5/site-packages/pihole_exporter/pihole_exporter.py", line 112, in make_server
    handler_class=self._SilentHandler)
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 160, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 51, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -9] Address family for hostname not supported

Kind Regards,
   Madic

**Comment by dr1s** [comment]
Flask was removed in favor of the official prometheus python client.

The problem here is the http server in python itself is not able to listen on IPv6 interfaces.
Further information can be found in this bug report: https://bugs.python.org/issue24209

I will try to workaround this issue when I have time. Maybe a different wsgi server implementation can do it.

**Comment by dr1s** [comment]
Commit c3482de should fix the issue.
Please try it out and let me know if it works for you.
My network is not running with IPv6 so I was only able to try it locally.

**Comment by Madic-** [comment]
Thank you. Will try it out as soon as I'm back from vacation with my family. So not before Friday the 7th September.
You can close the ticket. I will give you feedback if it worked or not

**Comment by dr1s** [comment]
Enjoy your vacation.

**Comment by Madic-** [comment]
I can confirm it's working again. Thank you

**Comment by dr1s** [comment]
Thanks for testing it!
