### ISSUE TITLE
NameError: name 'values' is not defined

### ISSUE THREAD

**Issue by runningman84** [dr1s/pihole_exporter.py#5]
I get this error message running the exporter in the same pod as pihole:
```
 NameError: name 'values' is not defined                                                                                                                                                              │
│ Traceback (most recent call last):                                                                                                                                                                   │
│   File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run                                                                                                                              │
│     self.result = application(self.environ, self.start_response)                                                                                                                                     │
│   File "pihole_exporter.py", line 132, in prometheus_app                                                                                                                                             │
│     output = self.generate_latest()                                                                                                                                                                  │
│   File "pihole_exporter.py", line 126, in generate_latest                                                                                                                                            │
│     self.get_exteneded_metrics()                                                                                                                                                                     │
│   File "pihole_exporter.py", line 98, in get_exteneded_metrics                                                                                                                                       │
│     'pihole_client_queries', client_data)                                                                                                                                                            │
│   File "/usr/local/lib/python3.7/site-packages/prometheus_metrics/exporter.py", line 45, in update                                                                                                   │
│     self.metrics[name].update(value)                                                                                                                                                                 │
│   File "/usr/local/lib/python3.7/site-packages/prometheus_metrics/metrics.py", line 172, in update                                                                                                   │
│     values_tmp = self.__update_old_values(values_tmp, values)                                                                                                                                        │
│   File "/usr/local/lib/python3.7/site-packages/prometheus_metrics/metrics.py", line 106, in __update_old_values                                                                                      │
│     old_values[label])                                                                                                                                                                               │
│   File "/usr/local/lib/python3.7/site-packages/prometheus_metrics/metrics.py", line 96, in __zero_missing_value                                                                                      │
│     for label in values:                                                                                                                                                                             │
│ NameError: name 'values' is not defined        
```
This is the corresponding helm chart:
https://github.com/runningman84/helm-charts/tree/master/pihole

**Comment by dr1s** [comment]
I just pushed a new version, please try this one out.
It fixes a few problems but I'm not sure if its related to your error.
the docker image is currently building and should be done in a few minutes.

The other option is that your error has something to do with the privacy level introduced after the exporter was initially created.
You could try to set it to 0 or disable the extended metrics (remove the `-e` [here](https://github.com/runningman84/helm-charts/blob/master/pihole/templates/deployment.yaml#L100))
