### ISSUE TITLE
Error while trying to get metrics from a remote pihole

### ISSUE THREAD

**Issue by proggaras** [dr1s/pihole_exporter.py#6]
Getting the following error while I try to get metrics from a remote pihole:
```
Unable to find: /etc/pihole/setupVars.conf,
* Listening on 0.0.0.0:9311,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open,
    encode_chunked=req.has_header('Transfer-encoding')),
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request,
    self._send_request(method, url, body, headers, encode_chunked),
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request,
    self.endheaders(body, encode_chunked=encode_chunked),
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders,
    self._send_output(message_body, encode_chunked=encode_chunked),
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output,
    self.send(msg),
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send,
    self.connect(),
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect,
    (self.host,self.port), self.timeout, self.source_address),
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection,
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):,
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo,
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):,
socket.gaierror: [Errno -2] Name does not resolve,
```
Start command: 
```
docker run -d --net=host -t dr1s/pihole_exporter --pihole 192.168.17.5 --auth xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
There is no DNS enty for: --pihole 192.168.17.5

**Comment by dr1s** [comment]
> There is no DNS enty for: --pihole 192.168.17.5
Why not? Pihole creates `pi.hole`by default.

**Comment by proggaras** [comment]
For any reason I don't know it is executing the the following function:
'''
def get_authentication_token():
'''
=> Unable to find: /etc/pihole/setupVars.conf,

For my understanding this should not happen as log I pass the "--auth xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" argument?

**Comment by dr1s** [comment]
Thats [correct](https://github.com/dr1s/pihole_exporter.py/blob/master/pihole_exporter/pihole_exporter.py#L181), if `--auth` is set it should not try to read `setupVars.conf`.

**Comment by proggaras** [comment]
Hm but if you check my first post. --auth was set and the first output in the log ist: "Unable to find: /etc/pihole/setupVars.conf,"

**Comment by dr1s** [comment]
I can't reproduce this on my machine, but this could mean that the arguments are not passed to the python script.
You could try to build the image by yourself or run it without docker.
